sudo: required
services:
  - docker

before_install:
  - docker build -t nodejs-boilerplate-server -f ./server/Dockerfile.dev ./server

install:
  - npm i --silent -g codecov
  - npm i --silent

script:
  - npm run lint
  - docker run -v /coverage:/app/server/test/coverage nodejs-boilerplate-server jest --config jest.config.js --runInBand

after_success:
  - codecov -f /coverage/lcov.info -t f00e25b3-f357-4c83-a4c4-c9a55950e2c2
